### ISSUE TITLE
Build fails on NVIDIA UNIX Open Kernel Module for x86_64  570.124.04

### ISSUE THREAD

**Issue by devbrones** [guibou/nixGL#199]
Hi, when building nixGL i recieve the following error:

`nix-env -iA nixgl.auto.nixVulkanNvidia --show-trace`

```
building '/nix/store/99svw939qi3i3ac9kb5alww1w5zgzryy-impure-nvidia-version-file.drv'...
error:
       … from call site
         at /nix/store/d5xzq5yl0lr6vz3kn59fjfgszq3zrd4a-nixgl/nixgl/nixGL.nix:154:25:
          153|       # TODO: 32bit version? Not tested.
          154|       nixVulkanNvidia = nixNvidiaWrapper "Vulkan";
             |                         ^
          155|     };

       … while calling 'nixNvidiaWrapper'
         at /nix/store/d5xzq5yl0lr6vz3kn59fjfgszq3zrd4a-nixgl/nixgl/nixGL.nix:115:26:
          114|       # TODO: 32bit version? Not tested.
          115|       nixNvidiaWrapper = api:
             |                          ^
          116|         writeExecutable {

       … from call site
         at /nix/store/d5xzq5yl0lr6vz3kn59fjfgszq3zrd4a-nixgl/nixgl/nixGL.nix:116:9:
          115|       nixNvidiaWrapper = api:
          116|         writeExecutable {
             |         ^
          117|           name = "nix${api}Nvidia-${version}";

       … while calling 'writeExecutable'
         at /nix/store/d5xzq5yl0lr6vz3kn59fjfgszq3zrd4a-nixgl/nixgl/nixGL.nix:22:21:
           21| let
           22|   writeExecutable = { name, text }:
             |                     ^
           23|     writeTextFile {

       … from call site
         at /nix/store/d5xzq5yl0lr6vz3kn59fjfgszq3zrd4a-nixgl/nixgl/nixGL.nix:23:5:
           22|   writeExecutable = { name, text }:
           23|     writeTextFile {
             |     ^
           24|       inherit name text;

       … while calling 'writeTextFile'
         at /nix/store/q0g476960hwygpfvidc75jgkfm96j1wv-nixpkgs/nixpkgs/pkgs/build-support/trivial-builders/default.nix:83:5:
           82|   writeTextFile =
           83|     { name
             |     ^
           84|     , text

       … in the condition of the assert statement
         at /nix/store/q0g476960hwygpfvidc75jgkfm96j1wv-nixpkgs/nixpkgs/pkgs/build-support/trivial-builders/default.nix:94:5:
           93|     }:
           94|     assert lib.assertMsg (destination != "" -> (lib.hasPrefix "/" destination && destination != "/")) ''
             |     ^
           95|       destination must be an absolute path, relative to the derivation's out path,

       … from call site
         at /nix/store/q0g476960hwygpfvidc75jgkfm96j1wv-nixpkgs/nixpkgs/pkgs/build-support/trivial-builders/default.nix:94:12:
           93|     }:
           94|     assert lib.assertMsg (destination != "" -> (lib.hasPrefix "/" destination && destination != "/")) ''
             |            ^
           95|       destination must be an absolute path, relative to the derivation's out path,

       … while calling 'assertMsg'
         at /nix/store/q0g476960hwygpfvidc75jgkfm96j1wv-nixpkgs/nixpkgs/lib/asserts.nix:39:21:
           38|   # TODO(Profpatsch): add tests that check stderr
           39|   assertMsg = pred: msg: pred || builtins.throw msg;
             |                     ^
           40|

       … in the left operand of the OR (||) operator
         at /nix/store/q0g476960hwygpfvidc75jgkfm96j1wv-nixpkgs/nixpkgs/lib/asserts.nix:39:31:
           38|   # TODO(Profpatsch): add tests that check stderr
           39|   assertMsg = pred: msg: pred || builtins.throw msg;
             |                               ^
           40|

       … in the left operand of the IMPL (->) operator
         at /nix/store/q0g476960hwygpfvidc75jgkfm96j1wv-nixpkgs/nixpkgs/pkgs/build-support/trivial-builders/default.nix:94:45:
           93|     }:
           94|     assert lib.assertMsg (destination != "" -> (lib.hasPrefix "/" destination && destination != "/")) ''
             |                                             ^
           95|       destination must be an absolute path, relative to the derivation's out path,

       … while evaluating a path segment
         at /nix/store/d5xzq5yl0lr6vz3kn59fjfgszq3zrd4a-nixgl/nixgl/nixGL.nix:117:35:
          116|         writeExecutable {
          117|           name = "nix${api}Nvidia-${version}";
             |                                   ^
          118|           text = ''

       error: cannot coerce null to a string: null

```

On Ubuntu 24.10 kernel version 6.11.0-19-generic\
`cat /proc/driver/nvidia/version`
```
NVRM version: NVIDIA UNIX Open Kernel Module for x86_64  570.124.04  Release Build  (dvs-builder@U22-I3-AF04-14-5)  Tue Feb 25 03:49:44 UTC 2025
GCC version:  gcc version 14.2.0 (Ubuntu 14.2.0-4ubuntu2) 
```

`inxi -G`
```
Graphics:
  Device-1: Intel TigerLake-H GT1 [UHD Graphics] driver: i915 v: kernel
  Device-2: NVIDIA GA106M [GeForce RTX 3060 Mobile / Max-Q] driver: nvidia
    v: 570.124.04
  Device-3: Sonix USB2.0 HD UVC WebCam driver: uvcvideo type: USB
  Display: wayland server: X.Org v: 24.1.2 with: Xwayland v: 24.1.2
    compositor: gnome-shell v: 47.0 driver: dri: iris
    gpu: i915,nvidia,nvidia-nvswitch resolution: 1: 1920x1080~60Hz
    2: 1920x1080~144Hz
  API: EGL v: 1.5 drivers: iris,nvidia,swrast
    platforms: gbm,wayland,x11,surfaceless,device
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: intel mesa
    v: 24.2.8-1ubuntu1~24.10.1 renderer: Mesa Intel UHD Graphics (TGL GT1)
  API: Vulkan v: 1.3.290 drivers: N/A surfaces: xcb,xlib,wayland
```
